name: Node.js CI

on:
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: 

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Set up environment variables
      env:
        API_KEY: ${{ secrets.API_KEY }}
        GIT_ACCESS_TOKEN: ${{ secrets.GIT_ACCESS_TOKEN }}
        GITHUB_USERNAME: ${{ secrets.USERNAME }}
        GITHUB_REPO_NAME: ${{ secrets.REPO_NAME }}
      run: |
        echo "API_KEY=$API_KEY" >> .env
        echo "GIT_ACCESS_TOKEN=$GIT_ACCESS_TOKEN" >> .env
        echo "USERNAME=$GITHUB_USERNAME" >> .env
        echo "REPO_NAME=$GITHUB_REPO_NAME" >> .env
    - run: npm ci
    - run: node index
